// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfAspNet.Models;

#nullable disable

namespace SelfAspNet.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250102152645_CreateArticle")]
    partial class CreateArticle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SelfAspNet.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "JavaScript",
                            CreatedAt = new DateTime(2023, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ますます便利になるTypeScript！",
                            Url = "https://codezine.jp/article/corner/992"
                        },
                        new
                        {
                            Id = 2,
                            Category = "JavaScript",
                            CreatedAt = new DateTime(2023, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Remixを通じてWebを学ぶ",
                            Url = "https://codezine.jp/article/corner/942"
                        },
                        new
                        {
                            Id = 3,
                            Category = "JavaScript",
                            CreatedAt = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(2023, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Web Componentsを基礎から学ぶ",
                            Url = "https://codezine.jp/article/corner/927"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Rails",
                            CreatedAt = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(2023, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Railsの新機能を知ろう！",
                            Url = "https://codezine.jp/article/corner/991"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Rails",
                            CreatedAt = new DateTime(2023, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Railsによるクライアントサイド開発入門",
                            Url = "https://codezine.jp/article/corner/919"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Rust",
                            CreatedAt = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "現場で役立つRust入門",
                            Url = "https://atmarkit.itmedia.co.jp/ait/series/36943/"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Rust",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "基本からしっかり学ぶRust入門",
                            Url = "https://atmarkit.itmedia.co.jp/ait/series/24844/"
                        });
                });

            modelBuilder.Entity("SelfAspNet.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Published")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sample")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Isbn = "978-4-7981-8094-6",
                            Price = 3960,
                            Published = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "翔泳社",
                            Sample = true,
                            Title = "独習Java"
                        },
                        new
                        {
                            Id = 2,
                            Isbn = "978-4-7981-7613-0",
                            Price = 3135,
                            Published = new DateTime(2023, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "翔泳社",
                            Sample = true,
                            Title = "Androidアプリ開発の教科書"
                        },
                        new
                        {
                            Id = 3,
                            Isbn = "978-4-8156-1948-0",
                            Price = 4400,
                            Published = new DateTime(2023, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "SBクリエイティブ",
                            Sample = true,
                            Title = "これからはじめるReact実践入門"
                        },
                        new
                        {
                            Id = 4,
                            Isbn = "978-4-296-07070-1",
                            Price = 2420,
                            Published = new DateTime(2023, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "日経BP",
                            Sample = false,
                            Title = "作って学べるHTML＋JavaScriptの基本"
                        },
                        new
                        {
                            Id = 5,
                            Isbn = "978-4-297-13685-7",
                            Price = 3520,
                            Published = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "技術評論社",
                            Sample = false,
                            Title = "Nuxt 3 フロントエンド開発の教科書"
                        },
                        new
                        {
                            Id = 6,
                            Isbn = "978-4-297-13288-0",
                            Price = 3520,
                            Published = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "技術評論社",
                            Sample = true,
                            Title = "JavaScript本格入門"
                        },
                        new
                        {
                            Id = 7,
                            Isbn = "978-4-627-85711-7",
                            Price = 2970,
                            Published = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "森北出版",
                            Sample = false,
                            Title = "Pythonでできる! 株価データ分析"
                        },
                        new
                        {
                            Id = 8,
                            Isbn = "978-4-7981-7556-0",
                            Price = 4180,
                            Published = new DateTime(2022, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "翔泳社",
                            Sample = true,
                            Title = "独習C#"
                        },
                        new
                        {
                            Id = 9,
                            Isbn = "978-4-8156-1336-5",
                            Price = 3740,
                            Published = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "SBクリエイティブ",
                            Sample = true,
                            Title = "これからはじめるVue.js 3実践入門"
                        },
                        new
                        {
                            Id = 10,
                            Isbn = "978-4-296-08014-4",
                            Price = 3190,
                            Published = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "日経BP",
                            Sample = false,
                            Title = "基礎からしっかり学ぶC#の教科書"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
